ALTER TABLE "qr_codes"
ADD COLUMN IF NOT EXISTS "style_preset" TEXT NOT NULL DEFAULT 'rounded',
ADD COLUMN IF NOT EXISTS "foreground_color" TEXT NOT NULL DEFAULT '#0F172A',
ADD COLUMN IF NOT EXISTS "background_color" TEXT NOT NULL DEFAULT '#FFFFFF';
