import axios, { AxiosError, type AxiosInstance } from 'axios';
import { API_MDC_BASE } from '../lib/runtimeEnv';
import { getAuthHeaders } from '../utils/authToken';

export type DeliveryChannel = 'whatsapp' | 'email' | 'sms' | string;

export interface CreatePrescriptionInput {
  patientId: string;
  title: string;
  instructions: string;
  medicines: Array<{
    name: string;
    dosage: string;
    frequency: string;
    durationDays: number;
  }>;
  [key: string]: unknown;
}

export interface Prescription {
  id: string;
  patientId: string;
  title?: string;
  instructions?: string;
  status?: string;
  createdAt?: string;
  [key: string]: unknown;
}

export interface DeliverPrescriptionResponse {
  success: boolean;
  message?: string;
  channel?: DeliveryChannel;
  deliveredAt?: string;
  [key: string]: unknown;
}

export interface AssignHomeworkInput {
  patientId: string;
  title: string;
  description: string;
  dueDate: string;
  status?: 'pending' | 'in_progress' | 'completed' | string;
  [key: string]: unknown;
}

export interface HomeworkItem {
  id: string;
  patientId: string;
  title: string;
  description?: string;
  dueDate?: string;
  status: 'pending' | 'in_progress' | 'completed' | string;
  createdAt?: string;
  updatedAt?: string;
  [key: string]: unknown;
}

export interface UpdateHomeworkInput {
  title?: string;
  description?: string;
  dueDate?: string;
  status?: 'pending' | 'in_progress' | 'completed' | string;
  [key: string]: unknown;
}

interface ApiEnvelope<T> {
  success?: boolean;
  message?: string;
  data?: T;
}

export interface MdcPrescriptionHomeworkApiError {
  message: string;
  status?: number;
  code?: string;
  details?: unknown;
}

const mdcHttp: AxiosInstance = axios.create({
  baseURL: API_MDC_BASE,
  withCredentials: true,
  headers: {
    'Content-Type': 'application/json',
  },
  timeout: 15000,
});

// Add Authorization header to all requests
mdcHttp.interceptors.request.use((config) => {
  const authHeaders = getAuthHeaders();
  config.headers = Object.assign(config.headers || {}, authHeaders);
  return config;
});

const unwrap = <T>(payload: T | ApiEnvelope<T>): T => {
  if (payload && typeof payload === 'object' && 'data' in payload) {
    const envelope = payload as ApiEnvelope<T>;
    if (envelope.data !== undefined) {
      return envelope.data;
    }
  }

  return payload as T;
};

const toApiError = (error: unknown): MdcPrescriptionHomeworkApiError => {
  if (axios.isAxiosError(error)) {
    const axiosError = error as AxiosError<{ message?: string; error?: string; details?: unknown }>;
    return {
      message:
        axiosError.response?.data?.message
        || axiosError.response?.data?.error
        || axiosError.message
        || 'Prescription/Homework request failed',
      status: axiosError.response?.status,
      code: axiosError.code,
      details: axiosError.response?.data?.details,
    };
  }

  if (error instanceof Error) {
    return { message: error.message };
  }

  return { message: 'Unexpected Prescription/Homework API error' };
};

const createMockPrescriptionPdf = async (id: string): Promise<Blob> => {
  const jsPdfModule = await import('jspdf');
  const JsPdfCtor = jsPdfModule.jsPDF || jsPdfModule.default;

  const pdf = new JsPdfCtor({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const createdAt = new Intl.DateTimeFormat(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date());

  pdf.setFontSize(16);
  pdf.text('MyDigitalClinic Prescription', 20, 20);
  pdf.setFontSize(11);
  pdf.text(`Prescription ID: ${id}`, 20, 30);
  pdf.text(`Generated: ${createdAt}`, 20, 37);
  pdf.text('This is a fallback prescription PDF generated by the frontend.', 20, 50);
  pdf.text('Please retry once backend PDF generation is available.', 20, 57);

  return pdf.output('blob');
};

const blobLooksLikePdf = async (blob: Blob): Promise<boolean> => {
  if (!blob || blob.size === 0) {
    return false;
  }

  const firstBytes = new Uint8Array(await blob.slice(0, 5).arrayBuffer());
  const signature = String.fromCharCode(...firstBytes);
  return signature === '%PDF-';
};

export const createPrescription = async (data: CreatePrescriptionInput): Promise<Prescription> => {
  try {
    const response = await mdcHttp.post<Prescription | ApiEnvelope<Prescription>>('/api/mdc/prescriptions', data);
    return unwrap<Prescription>(response.data);
  } catch (error) {
    console.error('createPrescription failed, using mock fallback', toApiError(error));
    return {
      id: `mock-prescription-${Date.now()}`,
      patientId: data.patientId,
      title: data.title,
      instructions: data.instructions,
      status: 'created',
      createdAt: new Date().toISOString(),
    };
  }
};

export const deliverPrescription = async (id: string, channel: DeliveryChannel): Promise<DeliverPrescriptionResponse> => {
  try {
    const response = await mdcHttp.post<DeliverPrescriptionResponse | ApiEnvelope<DeliverPrescriptionResponse>>(
      `/api/mdc/prescriptions/${encodeURIComponent(id)}/deliver`,
      { channel },
    );
    return unwrap<DeliverPrescriptionResponse>(response.data);
  } catch (error) {
    console.error('deliverPrescription failed, using mock fallback', toApiError(error));
    return {
      success: true,
      message: `Mock prescription delivered via ${channel}`,
      channel,
      deliveredAt: new Date().toISOString(),
    };
  }
};

export const getPrescriptionPDF = async (id: string): Promise<Blob> => {
  try {
    const response = await mdcHttp.get<Blob>(`/api/mdc/prescriptions/${encodeURIComponent(id)}/pdf`, {
      responseType: 'blob',
    });

    const contentTypeHeader = String(response.headers?.['content-type'] || '').toLowerCase();
    const returnedBlob = response.data;
    const hasPdfContentType = contentTypeHeader.includes('application/pdf') || returnedBlob.type.toLowerCase().includes('pdf');
    const hasPdfSignature = await blobLooksLikePdf(returnedBlob);

    if (!hasPdfContentType || !hasPdfSignature) {
      console.error('getPrescriptionPDF received non-PDF payload, using generated fallback PDF', {
        contentType: contentTypeHeader,
        blobType: returnedBlob.type,
        size: returnedBlob.size,
      });
      return createMockPrescriptionPdf(id);
    }

    return returnedBlob;
  } catch (error) {
    console.error('getPrescriptionPDF failed, using mock fallback', toApiError(error));
    return createMockPrescriptionPdf(id);
  }
};

export const assignHomework = async (data: AssignHomeworkInput): Promise<HomeworkItem> => {
  try {
    const response = await mdcHttp.post<HomeworkItem | ApiEnvelope<HomeworkItem>>('/api/mdc/homework', data);
    return unwrap<HomeworkItem>(response.data);
  } catch (error) {
    console.error('assignHomework failed, using mock fallback', toApiError(error));
    return {
      id: `mock-homework-${Date.now()}`,
      patientId: data.patientId,
      title: data.title,
      description: data.description,
      dueDate: data.dueDate,
      status: data.status || 'pending',
      createdAt: new Date().toISOString(),
    };
  }
};

export const getHomework = async (patientId: string): Promise<HomeworkItem[]> => {
  try {
    const response = await mdcHttp.get<HomeworkItem[] | ApiEnvelope<HomeworkItem[]>>(
      `/api/mdc/patients/${encodeURIComponent(patientId)}/homework`,
    );
    return unwrap<HomeworkItem[]>(response.data);
  } catch (error) {
    console.error('getHomework failed, using mock fallback', toApiError(error));
    return [
      {
        id: `mock-homework-${Date.now()}-1`,
        patientId,
        title: 'Daily breathing exercise',
        description: '10 minutes every morning',
        dueDate: new Date().toISOString(),
        status: 'pending',
      },
    ];
  }
};

export const updateHomework = async (id: string, data: UpdateHomeworkInput): Promise<HomeworkItem> => {
  try {
    const response = await mdcHttp.put<HomeworkItem | ApiEnvelope<HomeworkItem>>(
      `/api/mdc/homework/${encodeURIComponent(id)}`,
      data,
    );
    return unwrap<HomeworkItem>(response.data);
  } catch (error) {
    console.error('updateHomework failed, using mock fallback', toApiError(error));
    return {
      id,
      patientId: 'mock-p1',
      title: data.title || 'Mock homework',
      description: data.description || '',
      dueDate: data.dueDate,
      status: data.status || 'pending',
      updatedAt: new Date().toISOString(),
    };
  }
};
