import axios from 'axios';

const TWO_FACTOR_API_KEY = process.env.TWO_FACTOR_API_KEY || 'd189f856-3f2a-11f1-9800-0200cd936042';

/**
 * Sends a backend-generated OTP via 2factor.in.
 *
 * URL format:
 *   https://2factor.in/API/V1/{api_key}/SMS/{phone}/{otp_value}/{template_name}
 *
 * Template names (fixed, approved in 2factor dashboard):
 *   - 'Registration1'  →  for clinic/user registration
 *   - 'otp_login'      →  for login OTP
 *
 * The OTP is generated by our backend and stored as a hash for local verification.
 */
export const send2FactorOtp = async (
  phoneNumber: string,
  otp: string,
  templateName: 'Registration1' | 'otp_login',
): Promise<void> => {
  const cleanPhone = phoneNumber.replace(/[^0-9]/g, '');

  // Always log to console for debugging
  console.log('---------------------------------------------------');
  console.log(`[OTP Service] Sending SMS to ${cleanPhone}: ${otp}`);
  console.log(`[OTP Service] Template: ${templateName}`);
  console.log('---------------------------------------------------');

  // Production/Local: always attempt to send using 2factor custom OTP endpoint if key is present
  // URL: .../SMS/{phone}/{otp_value}/{template_name}
  const url = `https://2factor.in/API/V1/${TWO_FACTOR_API_KEY}/SMS/${cleanPhone}/${otp}/${templateName}`;

  try {
    const response = await axios.get(url);
    if (response.data?.Status === 'Error') {
      throw new Error(response.data.Details || '2Factor send failed');
    }
  } catch (error: any) {
    console.error('[2Factor Send Error]:', error.response?.data || error.message);
    throw new Error('Failed to send OTP. Please try again.');
  }
};
