import { useEffect } from 'react';
import { Link } from 'react-router-dom';

const sectionTitleClass = 'mt-10 text-xl font-semibold text-charcoal';

export default function TermsOfUsePage() {
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
  }, []);

  return (
    <main className="min-h-screen bg-cream px-4 py-10 md:px-6 md:py-14">
      <div className="mx-auto w-full max-w-5xl rounded-2xl border border-calm-sage/15 bg-white/95 p-6 shadow-soft-sm md:p-10">
        <p className="text-xs uppercase tracking-widest text-charcoal/50">Legal</p>
        <h1 className="mt-2 text-3xl font-semibold text-charcoal md:text-4xl">Terms of Use (Terms & Conditions)</h1>

        <p className="mt-4 text-sm leading-6 text-charcoal/75">
          This document is an electronic record in terms of the Information Technology Act, 2000 and the applicable
          rules and amended provisions relating to electronic records. This record is generated by a computer system
          and does not require any physical or digital signatures.
        </p>

        <p className="mt-3 text-sm leading-6 text-charcoal/75">
          This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries
          Guidelines) Rules, 2011, requiring publication of rules and regulations, privacy policy and terms of use for
          access to or use of www.Manas360.com (including related mobile site and application), referred to as the
          Platform.
        </p>

        <p className="mt-3 text-sm leading-6 text-charcoal/75">
          The Platform is owned by Manas360 Mental Wellness Pvt Ltd, incorporated under the Companies Act, 1956,
          with registered office at 6 MLV, Talaghatpura Kanakapura Road, Bengaluru 560062 (Platform Owner, we, us,
          our).
        </p>

        <section>
          <h2 className={sectionTitleClass}>Acceptance</h2>
          <p className="mt-3 text-sm leading-6 text-charcoal/75">
            Accessing, browsing or using the Platform indicates your agreement to these Terms of Use and all applicable
            policies incorporated by reference. If you transact on the Platform, you are subject to the policies
            applicable to such transaction.
          </p>
        </section>

        <section>
          <h2 className={sectionTitleClass}>Key Terms</h2>
          <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-charcoal/75">
            <li>You must provide true, accurate and complete information during and after registration.</li>
            <li>You are responsible for all actions performed through your registered account.</li>
            <li>Information on the Platform may contain inaccuracies; services are provided without specific warranties to the fullest extent permitted by law.</li>
            <li>Use of the Platform and Services is at your own risk and discretion.</li>
            <li>Platform content, design, layout and graphics are proprietary; unauthorized use may trigger legal action.</li>
            <li>You agree to pay applicable charges for availing Services.</li>
            <li>You shall not use the Platform for unlawful, illegal or prohibited purposes.</li>
            <li>Third-party links are governed by their own terms and privacy policies.</li>
            <li>Initiating a transaction creates a legally binding and enforceable contract with the Platform Owner.</li>
            <li>You agree to indemnify and hold harmless Platform Owner and its affiliates against third-party claims arising from your breach of these terms, policies or law.</li>
            <li>Neither party is liable for non-performance caused by force majeure events.</li>
            <li>These Terms are governed by laws of India, and disputes are subject to exclusive jurisdiction of courts in Bengaluru, Karnataka.</li>
            <li>All concerns regarding these Terms must be communicated through contact details provided on the Platform.</li>
          </ol>
        </section>

        <section>
          <h2 className={sectionTitleClass}>Modification of Terms</h2>
          <p className="mt-3 text-sm leading-6 text-charcoal/75">
            These Terms may be modified at any time without assigning reasons. You are responsible for periodically
            reviewing them. Any additional or conflicting terms proposed by a user are expressly rejected.
          </p>
        </section>

        <div className="mt-10 border-t border-calm-sage/15 pt-6 text-sm text-charcoal/65">
          <p>By using the Platform and Services, you confirm that you have read and agreed to these Terms.</p>
          <p className="mt-2">Registered Office: 6 MLV, Talaghatpura Kanakapura Road, Bengaluru 560062</p>
          <div className="mt-4 flex flex-wrap gap-4">
            <Link to="/privacy" className="underline underline-offset-4">Read Privacy Policy</Link>
            <Link to="/refunds" className="underline underline-offset-4">Read Cancellation & Refund Policy</Link>
            <Link to="/" className="underline underline-offset-4">Back to Home</Link>
          </div>
        </div>
      </div>
    </main>
  );
}
