// ═══════════════════════════════════════════════════════════════
// MyDigitalClinic — Multi-Therapist Accounts Service
// Path: backend/src/services/mydigitalclinic/MultiTherapistService.js
// Dependencies: Prisma
// ═══════════════════════════════════════════════════════════════

const prisma = require('../../lib/prisma');

const MAX_THERAPISTS = 5;

class MultiTherapistService {

  /**
   * Get clinic with all therapist slots
   */
  static async getClinicTherapists(clinicId) {
    const clinic = await prisma.mdcClinic.findUnique({
      where: { id: clinicId },
      select: {
        id: true,
        clinicCode: true,
        clinicName: true,
        maxTherapists: true,
        therapists: {
          orderBy: { slotNumber: 'asc' },
          select: {
            id: true,
            slotNumber: true,
            loginSuffix: true,
            displayName: true,
            role: true,
            specialization: true,
            isActive: true,
            userId: true,
            invitedAt: true,
            acceptedAt: true,
          }
        }
      }
    });

    if (!clinic) throw new Error('Clinic not found');

    return {
      clinicId: clinic.id,
      clinicCode: clinic.clinicCode,
      clinicName: clinic.clinicName,
      maxTherapists: clinic.maxTherapists,
      therapists: clinic.therapists,
      slotsUsed: clinic.therapists.length,
      slotsRemaining: clinic.maxTherapists - clinic.therapists.length,
    };
  }

  /**
   * Add a therapist slot. Slot number is auto-assigned (next available).
   * loginSuffix is auto-generated by DB trigger (clinic_code + slot_number).
   */
  static async addTherapist(clinicId, { displayName, specialization }) {
    // Check slot limit
    const clinic = await prisma.mdcClinic.findUnique({
      where: { id: clinicId },
      include: { therapists: { select: { slotNumber: true } } }
    });

    if (!clinic) throw new Error('Clinic not found');
    if (clinic.therapists.length >= (clinic.maxTherapists || MAX_THERAPISTS)) {
      throw new Error(`Maximum ${clinic.maxTherapists || MAX_THERAPISTS} therapists reached`);
    }

    // Find next available slot number
    const usedSlots = clinic.therapists.map(t => t.slotNumber);
    let nextSlot = 1;
    while (usedSlots.includes(nextSlot) && nextSlot <= MAX_THERAPISTS) nextSlot++;

    if (nextSlot > MAX_THERAPISTS) throw new Error('No available slots');

    // Determine role — slot 1 is always admin
    const role = nextSlot === 1 ? 'admin' : 'therapist';

    // Create therapist — loginSuffix generated by DB trigger
    const therapist = await prisma.mdcTherapist.create({
      data: {
        clinicId,
        slotNumber: nextSlot,
        displayName,
        role,
        specialization: specialization || null,
        loginSuffix: `${clinic.clinicCode}-${String(nextSlot).padStart(2, '0')}`, // fallback if no trigger
        invitedAt: new Date(),
      },
      select: {
        id: true,
        slotNumber: true,
        loginSuffix: true,
        displayName: true,
        role: true,
        specialization: true,
        isActive: true,
      }
    });

    // Audit log
    await prisma.mdcAuditLog.create({
      data: {
        clinicId,
        userId: null, // set by middleware
        action: 'therapist_added',
        entityType: 'therapist',
        entityId: therapist.id,
        details: { slotNumber: nextSlot, displayName, role },
      }
    });

    return therapist;
  }

  /**
   * Update therapist display name or specialization
   */
  static async updateTherapist(clinicId, therapistId, { displayName, specialization }) {
    const therapist = await prisma.mdcTherapist.findFirst({
      where: { id: therapistId, clinicId }
    });
    if (!therapist) throw new Error('Therapist not found');

    return await prisma.mdcTherapist.update({
      where: { id: therapistId },
      data: {
        ...(displayName !== undefined && { displayName }),
        ...(specialization !== undefined && { specialization }),
        updatedAt: new Date(),
      }
    });
  }

  /**
   * Deactivate a therapist slot (soft-delete, preserves data)
   */
  static async deactivateTherapist(clinicId, therapistId) {
    const therapist = await prisma.mdcTherapist.findFirst({
      where: { id: therapistId, clinicId }
    });
    if (!therapist) throw new Error('Therapist not found');
    if (therapist.role === 'admin') throw new Error('Cannot deactivate the clinic admin');

    return await prisma.mdcTherapist.update({
      where: { id: therapistId },
      data: { isActive: false, updatedAt: new Date() }
    });
  }

  /**
   * Authenticate by login suffix (e.g., MDC-7A3F-02)
   * Returns therapist + clinic context for JWT token
   */
  static async authenticateByLoginSuffix(loginSuffix) {
    const therapist = await prisma.mdcTherapist.findUnique({
      where: { loginSuffix },
      include: {
        clinic: {
          select: { id: true, clinicCode: true, clinicName: true, isActive: true }
        }
      }
    });

    if (!therapist) throw new Error('Invalid login ID');
    if (!therapist.isActive) throw new Error('This therapist account has been deactivated');
    if (!therapist.clinic.isActive) throw new Error('This clinic has been deactivated');

    return {
      therapistId: therapist.id,
      clinicId: therapist.clinic.id,
      clinicCode: therapist.clinic.clinicCode,
      clinicName: therapist.clinic.clinicName,
      slotNumber: therapist.slotNumber,
      loginSuffix: therapist.loginSuffix,
      displayName: therapist.displayName,
      role: therapist.role,
      specialization: therapist.specialization,
    };
  }
}

module.exports = MultiTherapistService;
