CREATE TYPE "CertificationLevel" AS ENUM ('ENTRY', 'PROFESSIONAL', 'MASTERY');

CREATE TABLE "certifications" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "shortTitle" TEXT,
  "subtitle" TEXT NOT NULL,
  "level" "CertificationLevel" NOT NULL,
  "levelBadge" TEXT NOT NULL,
  "journeyDescription" TEXT NOT NULL,
  "durationLabel" TEXT NOT NULL,
  "investmentLabel" TEXT NOT NULL,
  "monthlyIncomeLabel" TEXT,
  "modulesCount" INTEGER,
  "deliveryMode" TEXT,
  "sessionRateLabel" TEXT,
  "outcomeLabel" TEXT,
  "prerequisitesLabel" TEXT NOT NULL,
  "primaryCtaLabel" TEXT NOT NULL,
  "secondaryCtaLabel" TEXT NOT NULL DEFAULT 'Learn More',
  "isInvitationOnly" BOOLEAN NOT NULL DEFAULT false,
  "enrollmentOpen" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 100,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "certifications_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "certifications_slug_key" ON "certifications"("slug");
CREATE UNIQUE INDEX "certifications_code_key" ON "certifications"("code");
CREATE INDEX "certifications_level_sortOrder_idx" ON "certifications"("level", "sortOrder");
CREATE INDEX "certifications_isActive_sortOrder_idx" ON "certifications"("isActive", "sortOrder");

INSERT INTO "certifications" (
  "id", "slug", "code", "title", "shortTitle", "subtitle", "level", "levelBadge", "journeyDescription",
  "durationLabel", "investmentLabel", "monthlyIncomeLabel", "modulesCount", "deliveryMode", "sessionRateLabel", "outcomeLabel",
  "prerequisitesLabel", "primaryCtaLabel", "secondaryCtaLabel", "isInvitationOnly", "enrollmentOpen", "sortOrder", "metadata", "updatedAt"
) VALUES
(
  '11111111-1111-4111-8111-111111111111',
  'certified-practitioner',
  'CERT-PRACTITIONER',
  'Certified Practitioner',
  'Certified Practitioner',
  'Self-Directed Mental Wellness',
  'ENTRY',
  '🟦 Entry Level: Self-Directed Learning',
  'Start your mental wellness journey with patient psychoeducation and community impact',
  '3 Months',
  'Free',
  NULL,
  16,
  NULL,
  NULL,
  'Personal Wellness',
  'None',
  'Start Free',
  'Learn More',
  false,
  true,
  10,
  '{"future": {"enrollment": {"enabled": true}, "eligibilityTracking": {"enabled": true}, "certificateGeneration": {"templateKey": "CERT-PRACTITIONER-V1", "status": "planned"}}}'::jsonb,
  NOW()
),
(
  '22222222-2222-4222-8222-222222222222',
  'certified-asha-mental-wellness-champion',
  'CERT-ASHA-CHAMPION',
  'Certified ASHA Mental Wellness Champion',
  'Certified ASHA Champion',
  'Community Mental Health Detection',
  'ENTRY',
  '🟦 Entry Level: Self-Directed Learning',
  'Start your mental wellness journey with patient psychoeducation and community impact',
  '5 Weeks',
  'Free',
  '₹1,500+',
  5,
  'WhatsApp',
  NULL,
  NULL,
  'ASHA/community worker',
  'Enroll Free',
  'Learn More',
  false,
  true,
  20,
  '{"future": {"enrollment": {"enabled": true}, "eligibilityTracking": {"enabled": true}, "certificateGeneration": {"templateKey": "CERT-ASHA-CHAMPION-V1", "status": "planned"}}}'::jsonb,
  NOW()
),
(
  '33333333-3333-4333-8333-333333333333',
  'certified-nlp-therapist',
  'CERT-NLP-THERAPIST',
  'Certified NLP Therapist',
  'Certified NLP Therapist',
  'Life Coaching & Behavior Transformation',
  'PROFESSIONAL',
  '🟨 Professional Level: Clinical & Coaching Excellence',
  'Build your professional practice with recognized clinical credentials',
  '6 Weeks',
  '₹15,000',
  '₹16K-60K',
  NULL,
  NULL,
  '₹800-2K',
  NULL,
  'None',
  'Enroll Now',
  'Learn More',
  false,
  true,
  30,
  '{"future": {"enrollment": {"enabled": true}, "eligibilityTracking": {"enabled": true}, "certificateGeneration": {"templateKey": "CERT-NLP-THERAPIST-V1", "status": "planned"}}}'::jsonb,
  NOW()
),
(
  '44444444-4444-4444-8444-444444444444',
  'certified-psychologist',
  'CERT-PSYCHOLOGIST',
  'Certified Psychologist',
  'Certified Psychologist',
  'Advanced Therapy Mastery',
  'PROFESSIONAL',
  '🟨 Professional Level: Clinical & Coaching Excellence',
  'Build your professional practice with recognized clinical credentials',
  '10 Weeks',
  '₹20,000',
  '₹50K-87K',
  NULL,
  NULL,
  '₹2-3.5K',
  NULL,
  'M.Phil/Ph.D + RCI',
  'Enroll Now',
  'Learn More',
  false,
  true,
  40,
  '{"future": {"enrollment": {"enabled": true}, "eligibilityTracking": {"enabled": true}, "certificateGeneration": {"templateKey": "CERT-PSYCHOLOGIST-V1", "status": "planned"}}}'::jsonb,
  NOW()
),
(
  '55555555-5555-4555-8555-555555555555',
  'certified-psychiatrist',
  'CERT-PSYCHIATRIST',
  'Certified Psychiatrist',
  'Certified Psychiatrist',
  'Medical Management & Integrated Care',
  'PROFESSIONAL',
  '🟨 Professional Level: Clinical & Coaching Excellence',
  'Build your professional practice with recognized clinical credentials',
  '8 Weeks',
  '₹25,000',
  '₹75K-1.5L',
  NULL,
  NULL,
  '₹2.5-5K',
  NULL,
  'MD Psychiatry + NMC',
  'Enroll Now',
  'Learn More',
  false,
  true,
  50,
  '{"future": {"enrollment": {"enabled": true}, "eligibilityTracking": {"enabled": true}, "certificateGeneration": {"templateKey": "CERT-PSYCHIATRIST-V1", "status": "planned"}}}'::jsonb,
  NOW()
),
(
  '66666666-6666-4666-8666-666666666666',
  'certified-executive-therapist',
  'CERT-EXEC-THERAPIST',
  'Certified Executive Therapist',
  'Certified Executive Therapist',
  'Consciousness Work & Integrative Practice',
  'MASTERY',
  '🟪 Mastery Level: Consciousness Work',
  'Integrate Western psychology with Eastern wisdom for transformational therapy',
  '6 Months',
  '₹40,000',
  '₹70K-1.8L',
  NULL,
  NULL,
  '₹3.5-6K',
  NULL,
  'One of above 3 professional certs',
  'Enroll Now',
  'Learn More',
  false,
  true,
  60,
  '{"future": {"enrollment": {"enabled": true}, "eligibilityTracking": {"enabled": true}, "certificateGeneration": {"templateKey": "CERT-EXEC-THERAPIST-V1", "status": "planned"}}}'::jsonb,
  NOW()
);
